name: benevolent_crm_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  get_storage: ^2.1.1
  fl_chart: ^1.0.0
  package_info_plus: ^9.0.0
  flutter_advanced_drawer: ^1.5.0
  image_picker: ^1.1.2
  double_tap_to_exit: ^1.0.3
  lucide_icons: ^0.257.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.9.0
  url_launcher: ^6.3.2
  timeago: ^3.7.1
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.7.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21
  
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/Egg-Crm 1.png
    - assets/images/skype.png
    - assets/images/yahoo.png
    - assets/images/gmail.png
    - assets/vectors/back.svg
    - assets/images/logo1.png

  